import { NextResponse } from "next/server";
import OpenAI from "openai";


const systemPrompt = `You are a flashcard creator, your task is to generate conscise and effective flashcards based on given topic or content.You take in text and create multiple flashcards from it. Make sure to create exactly 10 flashcards.
Both front and back should be one sentence long.

{
    "flashcards" :[
      {
        "front": str,
        "back": str
      }
    ]
}`;


export async function POST(req){
    const openai =  new OpenAI()
    const data = await req.text();


    // role system contains initial instructuctions(system prompt), role user contains input provided by user
    const completion = await openai.chat.completions.create({
        messages: [
            {role :  'system', content : systemPrompt},
            {role : 'user', content: data}
        ],
        model: "gpt-4o",
        response_format : {type : 'json_object'},
    })

    // accesses 1st choice response generated by gpt
    const flashcards = JSON.parse(completion.choices[0].message.content)

    return NextResponse.json(flashcards.flashcard)

}